In [6]:
import numpy as np

numpy索引访问形式

In [7]:
arr = np.array([[1,2,3,4,5],[4,5,6,7,8],[7,8,9,10,11]])

In [8]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 4,  5,  6,  7,  8],
       [ 7,  8,  9, 10, 11]])

In [9]:
arr[1:,2:]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [10]:
arr[0,3:5]

array([4, 5])

使用整数函数或索引访问！ 使用元组的形式 而非list

In [13]:
arr[((0,1,2),(2,3,4))]

array([ 3,  7, 11])

In [14]:
# 访问 2 3 行的 列为（1，2，3）的元素
arr[1:,(1,2,3)]

array([[ 5,  6,  7],
       [ 8,  9, 10]])

In [16]:
list_data = [[1,2,3,4,5],[4,5,6,7,8],[7,8,9,10,11]]

In [18]:
list_data[1:]

[[4, 5, 6, 7, 8], [7, 8, 9, 10, 11]]